"""Inclusão de campo respondido

Revision ID: 14123535a5fe
Revises: baa23f0aeae8
Create Date: 2025-07-03 11:09:22.663554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14123535a5fe'
down_revision = 'baa23f0aeae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('respondido')

    # ### end Alembic commands ###
